# ---
# Docker Nginx
#ubuntu ver 
FROM debian
#FROM ubuntu:21.10
LABEL maintainer="vaf@itzapad.ru"
RUN echo "deb http://mirror.yandex.ru/debian bullseye main" > /etc/apt/sources.list && \
    apt update && apt -y upgrade && apt -y install nginx

